version: "3.9"
services:
  sagas-server:
    container_name: sagas-server
    image: sagas-image:1.0.0
    build: .
    ports:
      - 8087:8087
    networks:
      - sagas-network
networks:
  sagas-network:
    external: true
