version: "3.9"

services:
  client-server:
    container_name: client-server
    image: client-image:1.0.0
    build: .
    ports:
      - 8091:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://client-db:5432/ClientDB
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    networks:
      - client-network
    depends_on:
      - client-db
  client-db:
    container_name: client-db
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ClientDB
    volumes:
      - client-volume:/var/lib/postgresql/data
    networks:
      - client-network
networks:
  client-network:
    external: true

volumes:
  client-volume: