version: "3.9"

services:
  employee-server:
    container_name: employee-server
    image: employee-image:1.0.0
    build: .
    ports:
      - 8084:8084
    environment:
      - DATABASE_URL=jdbc:postgresql://employee-db:5432/EmployeeDB
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    networks:
      - employee-network
    depends_on:
      - employee-db
  employee-db:
    container_name: employee-db
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: EmployeeDB
    volumes:
      - employee-volume:/var/lib/postgresql/data
    networks:
      - employee-network
      
networks:
  employee-network:
    external: true

volumes:
  employee-volume: