version: '3.9'
services:
  rabbit-server:
    container_name: rabbit-server
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbit_definitions.json:/etc/rabbitmq/definitions.json
    command: >
      bash -c "rabbitmq-server & 
               sleep 10 && 
               rabbitmqctl import_definitions /etc/rabbitmq/definitions.json &&
               tail -f /dev/null"
    networks:
      - client-network
      - sagas-network
      - auth-network
      
networks:
  client-network:    
    external: true
  sagas-network:
    external: true
  auth-network:
    external: true