version: '3.9'
services:
  rabbit-server:
    container_name: broker
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbit_definitions.json:/etc/rabbitmq/definitions.json
    command: >
      bash -c "rabbitmq-server & 
               sleep 10 && 
               rabbitmqctl import_definitions /etc/rabbitmq/definitions.json &&
               tail -f /dev/null"    