version: "3.9"

services:
  java_app:
    container_name: java_app
    image: al-flight-java_app:1.0.0 
    build: .
    ports: # caractere '-' serve para especificar listas
      - 8084:8084
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/flight
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on: # garantir que o db jรก subiu
      - java_db
  java_db:
    container_name: java_db
    image: postgres:latest
    ports:
      - 5442:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flight