version: "3.9"

services:
  flight-server:
    container_name: flight-server
    image: flight-image:1.0.0
    build: .
    ports:
      - 8093:8093
    environment:
      - DATABASE_URL=jdbc:postgresql://flight-db:5432/FlightDB
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    networks:
      - flight-network
    depends_on:
      - flight-db
  flight-db:
    container_name: flight-db
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FlightDB
    volumes:
      - flight-volume:/var/lib/postgresql/data
    networks:
      - flight-network
      
networks:
  flight-network:
    external: true

volumes:
  flight-volume: